### ISSUE TITLE
Use Bazel modules

### ISSUE THREAD

**Issue by MarcoBonino** [blaizard/bazel-examples#1]
Hello!

Could you add an example using Bazel modules ?
I'm trying to follow what you did in toolchain-arm64-gcc example, but using bazel modules...
I can't use load in MODULE.bazel and I'm not sure how to do it.

Thanks!

**Comment by blaizard** [comment]
Hey, I just added an example using modules, have look: https://github.com/blaizard/bazel-examples/tree/main/toolchain-arm64-gcc-modules
Hope that helps :)

**Comment by MarcoBonino** [comment]
> Hey, I just added an example using modules, have look: https://github.com/blaizard/bazel-examples/tree/main/toolchain-arm64-gcc-modules Hope that helps :)

Thanks a lot for quickly adding the example! Was very useful!
